src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),

    path("foods/", include("foods.urls")),
    path("orders/", include("orders.urls")),
    path("dashboard/", include("panel.urls")),

    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("about/", AboutUsTemplateView.as_view(), name="about_us"),
    path("", IndexTemplateView.as_view(), name="index"),
]

src/foods/urls.py
from django.urls import path

from .views import *


app_name = "foods"


urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("category/<int:id>/", CategoryDetailView.as_view(), name="category_details"),
    path("search/", SearchView.as_view(), name="search"),
    path("<int:id>/", FoodDetailView.as_view(), name="food_details"),
    path("menu/", MenuListView.as_view(), name="menu")
]

src/orders/urls.py
from django.urls import path
from .views import *


app_name = "orders"


urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order_list"),
    path("cart/", cart, name="cart"),
    path("set/", SetOrderView.as_view(), name="set_order"),
    path("", IndexView.as_view(), name="index"),
    path("<str:datetime>/", OrderDetailView.as_view(), name="order_details"),
]

src/panel/urls.py
from django.urls import path

from .views import *



app_name = "panel"



authentication_urls = [
    path('login/', LoginView.as_view(), name='login'),
    path('send-otp/', SendOTPView.as_view(), name="send-otp"),
    path('logout/', logout, name="logout"),
]


dashboard_urls = [
    path("order/<int:order_id>/edit/", EditOrders.as_view(), name="edit_order"),
    path("order/<int:order_id>/approve/", approve_order, name="approve_order"),
    path("order/<int:order_id>/reject/", reject_order, name="reject_order"),
    path("order/<int:order_id>/pay/", pay_order, name="pay_order"),
    path("order/<int:order_id>/deliver/", deliver_order, name="deliver_order"),
    path("order/<int:order_id>/take/", take_responsibility, name="take_responsibility"),
    path("",dashboard, name="dashboard"),
]


analytics_urls = [
    path("analytics-api/", JsonAPI.as_view(), name="analytics-api"),
    path("analytics/", analytics, name="analytics"),
    path("download/<str:dataset_name>", download_dataset, name="dataset_download"),
]



urlpatterns = [
    *authentication_urls,
    *analytics_urls,
    *dashboard_urls
]

src/templates/base/customer_login.html
{% load static %}

<section id="book-table" class="bg-white">
    <div class="container">
        <h3 class="section-title mb-4 text-center">Want to Order? Enter your phone number</h3>
        <div class="row justify-content-center align-items-center">
            <form id="loginForm" method="post" action="{% url 'panel:login' %}" class="col-12 col-md-6 mb-4">
                {{form.errors}}
                {% csrf_token %}
                <label for="phone">Phone Number:</label>
                <input class="form-control" type="text" id="phone" name="phone" placeholder="09***" required>
                <button id="sendCodeBtn" type="button" class="btn btn-primary btn-block my-4 pt-2 pb-1 btn-lg">
                    <div class="h4" id="sendCodeBtn-text">Send OTP</div>
                </button>

                <label for="otp">Enter OTP:</label>
                <input type="text" id="OTP-INPUT-BOX" name="otp_code" class="form-control" placeholder="" required disabled>
                <button type="submit" id="OTP-ENTER-BUTTON" class="btn btn-primary btn-block my-4 pt-2 pb-1 btn-lg" disabled>
                    <div class="h4">Login</div>
                </button>
            </form>
            <div class="col-12 col-md-6">
                <img src="{% static 'images/phone2.jpeg' %}" alt=" " class="w-100 rounded shadow">
            </div>

        </div>
    </div>
</section>

<script>
    document.getElementById('sendCodeBtn').addEventListener('click', function() {
        var phoneNumber = document.getElementById('phone').value;
        var phoneRegex = /^0?9\d{9}$/;
        if (!phoneRegex.test(phoneNumber)) {
            alert('Please enter a valid phone number.');
            return;
        }
        var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        $.ajax({
            type: 'POST',
            url: "{% url 'panel:send-otp' %}",
            contentType: 'application/json',
            headers: { "X-CSRFToken": csrftoken },
            data: JSON.stringify({ phone: phoneNumber }),
            success: function() {
                document.getElementById('OTP-INPUT-BOX').removeAttribute('disabled');
                document.getElementById('OTP-ENTER-BUTTON').removeAttribute('disabled');
                document.getElementById('sendCodeBtn-text').textContent = "Resend code";
             },
            error: function() {
                alert('Failed to send OTP. Please try again.');
            }
        });
    });

    document.getElementById('OTP-INPUT-BOX').setAttribute('disabled', 'disabled');
    document.getElementById('OTP-ENTER-BUTTON').setAttribute('disabled', 'disabled');
</script>

src/templates/base/footer.html
{% load static %}
<div class="footer-mobile-text">

    <div class="py-4 border border-lighter border-bottom-0 border-left-0 border-right-0 bg-dark">
        <div class="container">
            <div class="row justify-content-between align-items-center text-center">
                <div class="col-md-3 text-md-left mb-3 mb-md-0">
                    <img src="{{ maininfo.icon.url }}" width="100" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, Pigga Landing page" class="mb-0">
                </div>
                <div class="col-md-9 text-md-right">
                    <a href="{% url 'orders:cart' %}" class="pr-5"><small class="font-weight-bold">Cart</small></a>
                    <a href="{% url 'orders:index' %}" class="pr-4"><small class="font-weight-bold">Orders</small></a>
                    <a href="{% url 'foods:menu' %}" class="px-3"><small class="font-weight-bold">Menu</small></a>
                    <a href="{% url 'foods:category_list' %}" class="px-3"><small class="font-weight-bold">Categories</small></a>
                    <a href="{% url 'about_us' %}" class="px-3"><small class="font-weight-bold">About Us</small></a>
                </div>
            </div>
        </div>
    </div>

    <footer class="border border-dark border-left-0 border-right-0 border-bottom-0 p-4 bg-dark">
        <div class="container">
            <div class="row align-items-center text-center text-md-left">
                <div class="col">
                    <p class="mb-0 small">© <script>document.write(new Date().getFullYear())</script>, <a href="https://github.com/Ramin-RX7/CafeMenu" target="_blank">Group1</a>  All rights reserved </p>
                </div>
                <div class="d-none d-md-block">
                    <h6 class="small mb-0">
                        {% for app_name,link in socials.items %}
                            <a href="{{link}}" class="px-2"><i class="ti-{{app_name}}"></i></a>
                        {% endfor %}
                    </h6>
                </div>
            </div>
        </div>
    </footer>
</div>

src/templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded shadow py-2">
      <div class="navbar-brand mx-md-5">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <a class="" href="/">
            <img src="{{ maininfo.icon.url }}" alt="" class="navbar-brand" width="50px">
         </a>
         <a class="" href="/">{{ maininfo.title }}</a>
      </div>

         <ul class="navbar-nav mx-lg-5">
            <li class="nav-item py-3">
               <a href="{% url 'orders:cart' %}" class="text-primary">
                  <svg class="text-primary" xmlns="http://www.w3.org/2000/svg" height="1.25em" viewBox="0 0 576 512"><style>svg{fill:#bc8c4c}</style><path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg>
               </a>
            </li>
         </ul>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav text-center">
            <li class="nav-item mx-2 mt-2">
               <a class="nav-link text-primary" href="{% url 'foods:menu' %}">Menu</a>
            </li>
            <li class="nav-item mx-2 mt-2">
               <a class="nav-link" href="{% url 'foods:category_list' %}">Categories</a>
            </li>
            <li class="nav-item mx-2 mt-2">
               <a class="nav-link" href="{% url 'orders:index' %}">Orders</a>
               <li class="nav-item mx-2 mt-2">
                  <a class="nav-link" href="{% url 'about_us' %}">About Us</a>
               </li>
            </li>
         </ul>
      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-2 py-3">
              <form action="{% url 'foods:search' %}" method="get" class="mx-5">
                  <input type="search" name="searched" placeholder="search in foods..." class="form-control me-2">
              </form>
            </li>
         </ul>
      </div>

</nav>