src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),

    path("foods/", include("foods.urls")),
    path("orders/", include("orders.urls")),
    path("dashboard/", include("panel.urls")),

    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("about/", AboutUsTemplateView.as_view(), name="about_us"),
    path("", IndexTemplateView.as_view(), name="index"),
]

src/foods/urls.py
from django.urls import path

from .views import *


app_name = "foods"


urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("category/<int:id>/", CategoryDetailView.as_view(), name="category_details"),
    path("search/", SearchView.as_view(), name="search"),
    path("<int:id>/", FoodDetailView.as_view(), name="food_details"),
    path("menu/", MenuListView.as_view(), name="menu")
]

src/orders/urls.py
from django.urls import path
from .views import *


app_name = "orders"


urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order_list"),
    path("cart/", cart, name="cart"),
    path("set/", SetOrderView.as_view(), name="set_order"),
    path("", IndexView.as_view(), name="index"),
    path("<str:datetime>/", OrderDetailView.as_view(), name="order_details"),
]

src/orders/models.py
from django.db import models

from core.models import BaseModel
from foods.models import Food
from users.models import User


class Table(BaseModel):
    name = models.CharField(unique=True, max_length=25)
    is_reserved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name} ({'reserved' if self.is_reserved else 'empty'})"

    @classmethod
    def get_available_table(cls):
        tables = cls.objects.all()
        for table in tables:
            if table.is_reserved is False:
                return table



class Order(BaseModel):
    customer = models.ForeignKey(User, models.PROTECT)
    table = models.ForeignKey(Table, on_delete=models.SET_NULL, null=True)
    discount = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)
    status_field = models.TextChoices("Status","Pending Rejected Approved Delivered Paid")
    status = models.CharField(choices=status_field.choices, max_length=10,default="Pending")
    responsible_staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="assigned_orders")

    @property
    def price(self):
        return sum([item.final_price for item in self.orderitem_set.all()])

    @property
    def final_price(self):
        return round(self.price / 100 * (self.discount or 100), 2)

    def __str__(self) -> str:
        return f"{self.customer}"

    @property
    def get_url_id(self):
        return self.created_at.strftime("%Y%m%d%H%M%S")


    def approve(self):
        self.status = "Approved"
        self.save()
    def reject(self):
        self.status = "Rejected"
        self.save()
    def deliver(self):
        self.status = "Delivered"
        self.save()
    def pay(self):
        self.status = "Paid"
        self.save()

    def take_responsibility(self, staff:User):
        self.responsible_staff = staff
        self.save()

    def save(self, check_items=True):
        if check_items:
            if not self.price:
                raise SystemError("No price given")
        super().save()


class OrderItem(BaseModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    unit_price = models.DecimalField(decimal_places=2, max_digits=5)
    discount = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)

    @property
    def final_price(self):
        return round(((100-self.discount)/100*self.unit_price)*self.quantity, 2)

    def __str__(self) -> str:
        return f"{self.quantity}"

    def save(self, *args, **kwargs):
        related_order_items = OrderItem.objects.filter(order=self.order, food=self.food).exclude(id=self.id)
        if len(related_order_items):
            total_quantity = sum([item.quantity for item in related_order_items])
            for item in related_order_items:
                item.delete()
            self.quantity = total_quantity + self.quantity
        super().save(*args, **kwargs)

src/orders/views.py
import json
from datetime import datetime, timedelta
from django.http import JsonResponse

from django.shortcuts import render,redirect
from django.db import transaction
from django.views import View
from django.views.generic import ListView,DetailView,RedirectView
from django.core.cache import caches

from foods.models import Food
from users.models import User
from .models import Order,Table,OrderItem



AUTH_CACHE = caches["default"]


class IndexView(ListView):
    model=Order
    template_name= 'orders/order_list.html'

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(customer=self.request.user).order_by("-created_at")
        return context


class OrderListView(RedirectView):
    pattern_name = 'orders:index'


class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order_details.html'
    context_object_name = 'order'

    def get_object(self, queryset=None):
        user = self.request.user
        if not user.is_authenticated:
            return redirect("orders:index")
        t = self.kwargs.get("datetime")
        interval = timedelta(seconds=1)
        orders = Order.objects.filter(
            customer = user,
            created_at__lte = datetime.strptime(t, "%Y%m%d%H%M%S") + interval,
            created_at__gte = datetime.strptime(t, "%Y%m%d%H%M%S") - interval,
        )
        if orders.exists():
            return orders.get()



class SetOrderView(View):
    def post(self, request):
        body = json.loads(request.body)
        data = body.get("cart")
        table_id = body.get("table")
        customer:User = request.user
        if not all([customer.is_authenticated,data,table_id]):
            return redirect("orders:cart")

        data = json.loads(data)
        discount = 0.0
        table = Table.objects.get(id=int(table_id))

        order = Order(customer=customer, table=table, discount=discount)

        with transaction.atomic():
            order.save(check_items=False)
            for food_id,quantity in data.items():
                food = Food.objects.get(id=food_id)
                orderitem = OrderItem(
                    order = order,
                    food = food,
                    quantity = int(quantity),
                    unit_price = food.price,
                    discount = food.discount
                )
                orderitem.save()
            session_orders = request.session.get("orders", [])
            session_orders.append(order.id)
            request.session["orders"] = session_orders
        return JsonResponse({}, status=200)


def cart(request):
    data = request.COOKIES.get("cart") or {}
    cart = {}
    cart_given = False
    if data:
        cart_given = True
        if (data:=json.loads(data)):
            for food_id,quantity in data.items():
                food = Food.objects.get(id=food_id)
                cart[food] = quantity
        del request.COOKIES["cart"]
    context = {"cart": cart, "cart_given":cart_given, "tables":Table.objects.all()}
    response = render(request, 'orders/cart.html', context)
    response.delete_cookie('cart')
    return response

src/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block title %} Cart {% endblock %}


{% block content %}


<section id="about2">
    <h6 class="section-subtitle text-center">Your</h6>
    <h3 class="section-title mb-6 pb-3 text-center">Cart</h3>
    <div class="container">
        <div class="row mt-3" style="justify-content:space-around;">
        {% if cart_given %}
            {% for food,quantity in cart.items %}
            <div class="card mb-3" style="max-width:90%;" id="food-{{food.id}}">
                <div class="row g-0">
                    <div class="col-md-6">
                        <img src="{{ food.image.url }}" class="img-fluid img-thumbnail p-3" alt="{{ food.title }}" style="height: 100%; width: 100%;">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body" style="padding-right:2% ;padding-right:3%;">
                            <h5 class="card-title text-primary">{{ food.title }}</h5>
                            <div class="custom-list">
                                <div class="info">
                                    <div class="head clearfix">
                                        <div class="title float-left" style="font-size: 16px;">For each</div>
                                        <div class="float-right" style="font-size: 16px;"><span id="unit-price-{{food.id}}">{{ food.price }}</span> $</div>
                                    </div>
                                    <div class="head clearfix">
                                        <div class="title float-left" style="font-size: 16px;">Quantity</div>
                                        <div id="item-quantity-{{food.id}}" class="float-right" style="font-size: 16px;">{{ quantity }}</div>
                                    </div>
                                    {% if food.discount %}
                                    <div class="head clearfix">
                                        <div class="title float-left " style="font-size: 16px;">Discount</div>
                                        <div class="float-right" style="font-size: 16px;"><span class="item-discount" id="discount-{{food.id}}">{{ food.discount }}</span>%</div>
                                    </div>
                                    {% endif %}
                                    <div class="head clearfix">
                                        <div class="title float-left " style="font-size: 16px;">Total</div>
                                        <div class="float-right" style="font-size: 16px;"><span class="item-total-price" id="total-price-{{food.id}}">{{ food.final_price|mul:quantity }}</span> $</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col py-3">
                                <form id="form-{{ food.id }}">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col">
                                            <input type="number" name="quantity" id="" class="quantity-input form-control" value="{{quantity}}" min="1" max="50" style="width: 80%;">
                                        </div>
                                        <div class="col py-1">
                                            <button type="submit" name="food" value="{{ food.id }}" data-id="{{ food.id }}" class="add-button btn btn-info btn-block">Change</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col py-2">
                                <button name="food" value="{{ food.id }}" class="btn btn-danger btn-block del-button">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="text-center">
                <h3 class="text-center">Your cart is empty</h3>
                <br><br>
                <h4 class="text-center">Check out our menu to add foods to your cart</h4>
                <br>
                <a href="{% url 'foods:menu' %}"><button class="btn btn-primary btn-lg">Menu</button></a>
                <br>
            </div>
            {% endfor %}
        {% else %}
            <script>
                function setCookie(name, value, days) {
                    const expires = new Date();
                    expires.setTime(expires.getTime() + (days * 24 * 60 * 60 * 1000));
                    document.cookie = `${name}=${value};expires=${expires.toUTCString()};path=/`;
                }
                let cartData = JSON.parse(localStorage.getItem('cart'));
                let cartDataString = JSON.stringify(cartData);
                setCookie('cart', cartDataString, 0.01);
                window.location.href = window.location.href;
            </script>
        {% endif %}
        </div>
    </div>


    {% if cart %}
    <div class="container text-center head clearfix py-5" >
        <div class="col">
            <h4 class="py-2">Total orders price : <span class="text-primary" id="total-price"></span> </h4>
        </div>

        <div class="col row d-flex justify-content-center my-5">
            <select name="" id="selected-table" class="col-12 col-md-4">
                <option value="" class="form-control" disabled selected>Select your table</option>
                {% for table in tables %}
                    <option value="{{table.id}}" class="form-control">{{table.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col py-2">
            {% if cart %}
                {% if logged_in %}
                <button id="sendDataButton" class="btn btn-success"  style="width: 50%;"><h4 style="padding-top:3%;">Set Order</h4></button>
                <form id="orderForm" action="{% url 'orders:set_order' %}" method="post">
                    {% csrf_token %}
                </form>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div id="popup" class="popup">
        <div class="popup-content">
            Item added to cart!
        </div>
    </div>
</section>


<script src="{% static 'js/cart.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        calculateCart()
    });
</script>

{% endblock %}

src/templates/orders/order_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Order Details {% endblock %}

{% load filters %}
{% block content %}

<section id="about2">

  {% if order %}
    <h3 class="section-title pb-3 text-center">Your Order</h3>
    <div class="container">
        <div class="section-devider my-6 transparent"></div>
        <h4 class="float-left title">Order</h4>
    </div>
    <br>
    <hr>
    <div class="container">
        <h5 class="text-primary">Order details</h5>
    </div>
    <div class="container">
        <div class="head py-2">
            <div class="float-left" style="font-size: 20px;">Status : <span class="text-primary" style="font-size: 20px;" id="status">{{order.status}}</span></div>
            <br>
        </div>
        <div class="row mt-3">
            {% for item in order.orderitem_set.all %}
            <div class="col-md-6 mb-4">
                <div class="custom-list">
                    <div class="info">
                        <div class="head clearfix">
                          <div class="title float-left text-primary " style="font-size: 20px;">{{ item.food }}</div>
                          <div class="float-right" style="font-size: 20px;">{{ item.unit_price }} $</div>
                        </div>
                        <div class="body">
                            <div class="float-left" style="font-size: 18px;">Quantity : </div>
                            <div class="float-right" style="font-size: 18px;">{{ item.quantity }}</div>
                        </div>

                        <div class="body">
                            <div class="float-left" style="font-size: 18px;">Discount : </div>
                            <div class="float-right" style="font-size: 18px;">{{ item.discount }} %</div>
                        </div>
                        <div class="body">
                            <div class="float-left" style="font-size: 18px;">Total :</div>
                            <div class="float-right" style="font-size: 18px;">{{ item.final_price }} $</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="container">
            <div class="custom-list">
                <div class="info">
                    <div class="head clearfix">
                        <div class="title text-center" style="font-size: 25px;">Total Price : <h class="text-primary" style="font-size: 25px;"> {{order.price}}$</h></div>
                    </div>
                    <div class="body">
                        <div class="title text-center" style="font-size: 20px; color: #000;"> Order submitted at : {{order.created_at}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {% else %}
    <div class="container d-flex align-items-center" style="flex-direction: column;">
        <div class="section-devider my-6 transparent"></div>
        <h2 class="float-center title text-center">Order not found!</h2>
        <div class="section-devider my-4 transparent"></div>
        <button class="float-center btn btn-primary"><a href="{% url 'orders:index' %}" class="text-white h5">Orders</a></button>
        <div class="section-devider my-6 transparent"></div>
    </div>
  {% endif %}


</section>

<script>
    function checkForUpdate() {
        var currentUrl = window.location.href;
        $.ajax({
            url: currentUrl,
            method: 'GET',
            success: function(response) {
                var tempDiv = document.createElement('div');
                tempDiv.innerHTML = response;
                var elementToCheck = tempDiv.querySelector('#status');
                console.log(elementToCheck)
                if (elementToCheck.textContent != document.getElementById("status").textContent) {
                    // location.reload();
                    document.getElementById("status").textContent = elementToCheck.textContent
                }
            },
            error: function(error) {
                console.error('Error checking for update:', error);
            }
        });
    }
    setInterval(checkForUpdate, 15000);
</script>


{% endblock %}

src/templates/orders/order_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Orders {% endblock %}

{% load filters %}
{% block content %}

<section id="about2">
    <h2 class="section-title text-center text-primary">Your Orders</h2>
    {% for order in orders %}
    <div class="container">
        <div class="section-devider my-4 transparent"></div>
        <h4 class="float-left title">Order {{forloop.counter}}</h4>
    </div>
    <br>
    <hr>
    <div class="container">
        <div class="row mt-3 mb-5">
            <div class="col-md-6">
                <h5 class="text-primary"><a href="{% url 'orders:order_details' order.get_url_id %}">Order details</a></h5>
                <div class="head py-2">
                    <div class="title float-left  " style="font-size: 20px;">Status :</div>
                    <div class="float-right text-primary" style="font-size: 20px;">{{order.status}}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row mt-3">
            {% for item in order.orderitem_set.all %}
                <div class="col-md-6 mb-4">
                    <div class="custom-list">
                        <div class="info">
                            <div class="head clearfix">
                              <div class="title float-left text-primary " style="font-size: 20px;">{{ item.food }}</div>
                              <div class="float-right" style="font-size: 20px;">{{ item.unit_price }} $</div>
                            </div>
                            <div class="body">
                                <div class="float-left" style="font-size: 18px;">Quantity : </div>
                                <div class="float-right" style="font-size: 18px;">{{ item.quantity }}</div>
                            </div>

                            <div class="body">
                                <div class="float-left" style="font-size: 18px;">Discount : </div>
                                <div class="float-right" style="font-size: 18px;">{{ item.discount }} %</div>
                            </div>
                            <div class="body">
                                <div class="float-left" style="font-size: 18px;">Total :</div>
                                <div class="float-right" style="font-size: 18px;">{{ item.final_price }} $</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="container">
            <div class="custom-list">
                <div class="info">
                    <div class="head clearfix">
                        <div class="title text-center" style="font-size: 25px;">Total Price : <h class="text-primary" style="font-size: 25px;"> {{order.final_price}}$</h></div>
                    </div>
                    <div class="body">
                        <div class="title text-center" style="font-size: 20px; color: #000;"> Order submitted at : &nbsp {{order.created_at}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% empty %}
    <h3 class="pb-3 text-center text-secondary my-5">You haven't ordered yet</h3>
    <br><br><br><br><br>
    {% endfor %}
</section>
{% endblock %}