src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),

    path("foods/", include("foods.urls")),
    path("orders/", include("orders.urls")),
    path("dashboard/", include("panel.urls")),

    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("about/", AboutUsTemplateView.as_view(), name="about_us"),
    path("", IndexTemplateView.as_view(), name="index"),
]

src/foods/urls.py
from django.urls import path

from .views import *


app_name = "foods"


urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("category/<int:id>/", CategoryDetailView.as_view(), name="category_details"),
    path("search/", SearchView.as_view(), name="search"),
    path("<int:id>/", FoodDetailView.as_view(), name="food_details"),
    path("menu/", MenuListView.as_view(), name="menu")
]

src/orders/urls.py
from django.urls import path
from .views import *


app_name = "orders"


urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order_list"),
    path("cart/", cart, name="cart"),
    path("set/", SetOrderView.as_view(), name="set_order"),
    path("", IndexView.as_view(), name="index"),
    path("<str:datetime>/", OrderDetailView.as_view(), name="order_details"),
]

src/foods/models.py
from django.db import models
from core.models import BaseModel



class Category(BaseModel):
    title = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/categories/', null=True)

    def __str__(self) -> str:
        return self.title


class Food(BaseModel):
    title = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/foods/', null=True)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    discount = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True)

    @property
    def final_price(self):
        return round(self.price * (100-self.discount) / 100 , 2)

    def __str__(self) -> str:
        return self.title

src/foods/forms.py
from django import forms
from . import models


class CategoryForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.widgets.ClearableFileInput(
            attrs={'accept': 'image/*'}
        ),
        required=False
    )
    delete_image = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'delete-image-checkbox'}))

    class Meta:
        model = models.Category
        fields = '__all__'


class FoodForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.widgets.ClearableFileInput(
            attrs={'accept': 'image/*'}
        ),
        required=False
    )
    delete_image = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'delete-image-checkbox'}))

    class Meta:
        model = models.Food
        fields = '__all__'

src/foods/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.db.models import Count
from django.views import View
from django.views.generic import ListView,DetailView


from .models import Category,Food


class CategoryListView(ListView):
    model = Category
    template_name = 'foods/category_list.html'
    context_object_name = "categories"



class CategoryDetailView(DetailView):
    model = Category
    template_name = 'foods/category_details.html'
    context_object_name = 'category'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()
        context['foods'] = category.food_set.all()
        return context


class FoodDetailView(DetailView):
    model=Food
    template_name="foods/food_details.html"
    pk_url_kwarg='id'
    context_object_name='food'


class SearchView(View):
    def get(self, request):
        searched = request.GET.get('searched')
        FOODS_QUERYSET = Food.objects.filter(title__contains=searched).distinct()
        return render(request, 'foods/search.html', {'searched':searched, "foods":FOODS_QUERYSET})



class MenuListView(ListView):
    model = Category
    template_name = 'foods/menu.html'
    context_object_name = 'categories'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(
            num_foods=Count('food')
        ).filter(num_foods__gt=0).prefetch_related('food_set').order_by('pk')
        return queryset

src/templates/foods/category_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Categories: {{ category.title }} {% endblock %}


{% block content %}


<section id="service" class="" style="background-image: url({% static 'images/style-4.png' %});">
  <div class="container raise-2">
      <h6 class="section-subtitle text-center">Foods in</h6>
      <h3 class="section-title mb-6 pb-3 text-center">{{category.title}}</h3>
      <div class="row">
        {% for food in category.food_set.all %}
        <div class="col-md-6 mb-4 equal-height-col">
            <a href="{% url 'foods:food_details' food.id %}" class="custom-list">
                <div class="row">
                    <div class="col-md-6 col-sm-9 text-center">
                        <div class="" style="">
                            {% if food.image %}
                              <img src="{{ food.image.url }}" alt="" class="rounded" style="width: 80%;">
                            {% else %}
                              <img src="{% static 'images/defaults/category.jpeg' %}" alt="" class="w-100 rounded shadow food-image">
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-9">
                        <div class="info">
                            <div class="head clearfix">
                                <p class="float-left">{{ food.title }}</p>
                                <p class="float-right text-primary">{% if food.discount %}<s>{{ food.price }}</s>{% endif %} {{food.final_price}}$</p>
                            </div>
                            <div class="body">
                                <p>{{ food.description|truncatechars:90 }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% if food.is_active %}
            <form id="form-{{ food.id }}" class="mt-3 mb-4" style="display: flex;">
                {% csrf_token %}
                <button type="submit" name="food" value="{{ food.id }}" data-id="{{ food.id }}" class="add-button btn btn-primary btn-block" style="align-items: center;margin-right: 1rem;display: grid;">Add to Cart</button>
                <span class="input-group-btn">
                    <button type="button" class="btn btn-secondary h-100 decreaseBtn" id="" data-food-id="{{food.id}}">-</button>
                </span>
                <input type="number" name="quantity" id="input-food-{{food.id}}" class="quantity-input form-control text-center" value="1" min="1" max="50" style="width: 20%;">
                <span class="input-group-btn">
                    <button type="button" class="btn btn-secondary h-100 increaseBtn" id="" data-food-id="{{food.id}}">+</button>
                </span>
            </form>
            {% else %}
            <div class="mt-3 text-secondary ml-3 ml-lg-5"><i>Unfortunately this food is not available for now</i></div>
            {% endif %}
        </div>
        {% empty %}
        <h3 class="text-center">Unfortunately this category is still empty.</h3>
        <br>
        <h3 class="text-center">Check out later to see foods here</h3>
        {% endfor %}
    </div>
  </div>

  <!-- <div id="popup" class="popup"> -->
    <!-- <div class="popup-content"> -->
        <!-- Item added to cart! -->
    <!-- </div> -->
  <!-- </div> -->
  <div class="section-devider my-4 transparent"></div>
  <a href="{% url 'orders:cart' %}" class="cart-icon px-3 py-4 mx-2">
      <img src="{% static 'images/cart.png' %}" alt="" height="35px" class="text-primary">
  </a>

</section>


<script src="{% static 'js/menu.js' %}"></script>

{% endblock %}

src/templates/foods/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Categories {% endblock %}

{% block content %}

<section id="about2">
  <h6 class="section-subtitle text-center">Menu</h6>
  <h3 class="section-title mb-5 pb-3 text-center">Categories</h3>

  {% for category in categories %}
  <div class="container">
        <div class="section-devider my-4 transparent"></div>
        <div class="row align-items-center">
            <div class="col-12 col-md-6 order-1 order-md-1">
            <a href="{% url 'foods:category_details' category.id %}">
                {% if category.image %}
                    <img src="{{ category.image.url }}" alt="" class="w-100 rounded shadow">
                {% else %}
                    <img src="{% static 'images/defaults/category.jpeg' %}" alt="" class="w-100 rounded shadow">
                {% endif %}
            </a>
            </div>

            <div class="col-12 col-md-6 order-2 order-md-2 mt-3 mt-md-0">
                <h3 class="section-title"><a href="{% url 'foods:category_details' category.id %}">{{category.title}}</a></h3>
                <p>{{ category.description|truncatewords:50 }}</p>
            </div>
        </div>
  </div>
  {% endfor %}

  <div class="section-devider my-4 transparent"></div>
  <a href="{% url 'orders:cart' %}" class="cart-icon px-3 py-4 mx-2 mt-2">
    <img src="{% static 'images/cart.png' %}" alt="" height="35px" class="text-primary">
  </a>

</section>

{% endblock %}

src/templates/foods/food_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ food.title }} {% endblock %}

{% block content %}


<section id="service" class="" style="background-image: url({% static 'images/style-4.png' %});">
    <div class="container raise-2">
        <div class="row justify-content-center">
            <div class="img-holder text-center">
                {% if food.image %}
                    <img src="{{ food.image.url }}" alt="" style="width: 75%;">
                {% else %}
                    <img src="{% static 'images/defaults/food.jpeg' %}" alt="">
                {% endif %}
            </div>
            <div class="col-md-8 mb-4">
                <div class="info">
                    <div class="head clearfix mt-5">
                        <h1 class="float-left">{{ food.title }}</h1>
                        <h1 class="float-right text-primary">{% if food.discount %}<s>{{ food.price }}</s>{% endif %} {{food.final_price}}$</h1>
                    </div>
                </div>
                {% if food.is_active %}
                <form id="form-{{ food.id }}" class="mt-3 mb-4" style="display: flex;">
                    {% csrf_token %}
                    <button type="submit" name="food" value="{{ food.id }}" data-id="{{ food.id }}" class="add-button btn btn-primary btn-block" style="align-items: center;margin-right: 1rem;display: grid;">Add to Cart</button>
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 decreaseBtn" id="" data-food-id="{{food.id}}">-</button>
                    </span>
                    <input type="number" name="quantity" id="input-food-{{food.id}}" class="quantity-input form-control text-center" value="1" min="1" max="50" style="width: 20%;">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 increaseBtn" id="" data-food-id="{{food.id}}">+</button>
                    </span>
                </form>
                {% else %}
                <div class="mt-3 text-secondary ml-3 ml-lg-5"><i>Unfortunately this food is not available for now</i></div>
                {% endif %}
                <div class="body mt-4">
                    <p>{{ food.description }}</p>
                </div>
            </div>
        </div>
    </div>

    <!-- <div id="popup" class="popup"> -->
        <!-- <div class="popup-content"> -->
            <!-- Item added to cart! -->
        <!-- </div> -->
    <!-- </div> -->

    <div class="section-devider my-4 transparent"></div>
    <a href="{% url 'orders:cart' %}" class="cart-icon px-3 py-4 mx-2">
        <img src="{% static 'images/cart.png' %}" alt="" height="35px" class="text-primary">
    </a>

</section>


<script src="{% static 'js/menu.js' %}"></script>
{% endblock %}

src/templates/foods/menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Menu {% endblock %}

{% block extra_style %}
{% endblock %}


{% block content %}

<div class="sticky-top bg-light">
    <div class="nav d-flex justify-content-center pl-4 flex-nowrap overflow-auto">
        {% for category in categories %}
            <a href="#{{ category.id }}" class="nav-item text-center mx-3 my-2">
                <img src="{{category.image.url}}" alt="" class="sticky-category-image">
                <div href="">{{category.title}}</div>
            </a>
        {% endfor %}
    </div>
</div>



<section id="about2" style="background-image: url({% static 'images/style-4.png' %});">
    <h3 class="section-title pb-3 text-center">Menu</h3>
    {% for category in categories %}
    <div class="container position-relative category-section" id="{{category.id}}">

        <div class="section-devider my-4 transparent"></div>
        <div class="row align-items-center mb-4">
            <div class="col-md-6">
                <a href="{% url 'foods:category_details' category.id %}">
                    <div class="category-img">
                        {% if category.image %}
                          <img src="{{ category.image.url }}" alt="" class="w-100 rounded shadow category-image">
                        {% else %}
                          <img src="{% static 'images/defaults/category.jpeg' %}" alt="" class="w-100 rounded shadow category-image">
                        {% endif %}
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <div class="caption">
                    <h6 class="section-subtitle">Category</h6>
                    <h3 class="section-title text-lg-left text-md-center"><a href="{% url 'foods:category_details' category.id %}">{{category.title}}</a></h3>
                    <p>{{ category.description|truncatewords:40 }}</p>
                </div>
            </div>
        </div>

        <div class="row mt-3 equal-height-row">
            {% for food in category.food_set.all %}
            <div class="col-md-6 mb-4 equal-height-col">
                <a href="{% url 'foods:food_details' food.id %}" class="custom-list">
                    <div class="row">
                        <div class="col-md-6 col-sm-9 text-center">
                            <div class="" style="">
                                {% if food.image %}
                                  <img src="{{ food.image.url }}" alt="" class="rounded" style="width: 80%;">
                                {% else %}
                                  <img src="{% static 'images/defaults/category.jpeg' %}" alt="" class="w-100 rounded shadow food-image">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-9">
                            <div class="info">
                                <div class="head clearfix">
                                    <p class="float-left">{{ food.title }}</p>
                                    <p class="float-right text-primary">{% if food.discount %}<s>{{ food.price }}</s>{% endif %} {{food.final_price}}$</p>
                                </div>
                                <div class="body">
                                    <p>{{ food.description|truncatechars:90 }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% if food.is_active %}
                <form id="form-{{ food.id }}" class="mt-3 mb-4" style="display: flex;">
                    {% csrf_token %}
                    <button type="submit" name="food" value="{{ food.id }}" data-id="{{ food.id }}" class="add-button btn btn-primary btn-block" style="align-items: center;margin-right: 1rem;display: grid;">Add to Cart</button>
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 decreaseBtn" id="" data-food-id="{{food.id}}">-</button>
                    </span>
                    <input type="number" name="quantity" id="input-food-{{food.id}}" class="quantity-input form-control text-center" value="1" min="1" max="50" style="width: 20%;">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 increaseBtn" id="" data-food-id="{{food.id}}">+</button>
                    </span>
                </form>
                {% else %}
                <div class="mt-3 text-secondary ml-3 ml-lg-5"><i>Unfortunately this food is not available for now</i></div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

    <div class="section-devider my-4 transparent"></div>
    <a href="{% url 'orders:cart' %}" class="cart-icon px-3 py-4 mx-2">
        <img src="{% static 'images/cart.png' %}" alt="" height="35px" class="text-primary">
    </a>

    <div id="popup" class="popup">
        <div class="popup-content">
            Item added to cart!
        </div>
    </div>

</section>




<script src="{% static 'js/menu.js' %}"></script>


{% endblock %}

src/templates/foods/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Search {% endblock %}



{% block content %}
<section id="service" class="pattern-style-4 has-overlay" style="background-image: url({% static 'images/style-4.png' %});">
    <div class="container">
        <h6 class="text-center">Foods containing:</h6>
        <h3 class="section-title mb-6 pb-3 text-center">{{ searched }}</h3>
        <div class="row">
            {% for food in foods %}
            <div class="col-md-6 mb-4 equal-height-col">
                <a href="{% url 'foods:food_details' food.id %}" class="custom-list">
                    <div class="row">
                        <div class="col-md-6 col-sm-9 text-center">
                            <div class="" style="">
                                {% if food.image %}
                                <img src="{{ food.image.url }}" alt="" class="rounded" style="width: 80%;">
                                {% else %}
                                <img src="{% static 'images/defaults/category.jpeg' %}" alt="" class="w-100 rounded shadow food-image">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-9">
                            <div class="info">
                                <div class="head clearfix">
                                    <p class="float-left">{{ food.title }}</p>
                                    <p class="float-right text-primary">{% if food.discount %}<s>{{ food.price }}</s>{% endif %} {{food.final_price}}$</p>
                                </div>
                                <div class="body">
                                    <p>{{ food.description|truncatechars:90 }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% if food.is_active %}
                <form id="form-{{ food.id }}" class="mt-3 mb-4" style="display: flex;">
                    {% csrf_token %}
                    <button type="submit" name="food" value="{{ food.id }}" data-id="{{ food.id }}" class="add-button btn btn-primary btn-block" style="align-items: center;margin-right: 1rem;display: grid;">Add to Cart</button>
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 decreaseBtn" id="" data-food-id="{{food.id}}">-</button>
                    </span>
                    <input type="number" name="quantity" id="input-food-{{food.id}}" class="quantity-input form-control text-center" value="1" min="1" max="50" style="width: 20%;">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-secondary h-100 increaseBtn" id="" data-food-id="{{food.id}}">+</button>
                    </span>
                </form>
                {% else %}
                <div class="mt-3 text-secondary ml-3 ml-lg-5"><i>Unfortunately this food is not available for now</i></div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<script src="{% static 'js/menu.js' %}"></script>





<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>



{% endblock content %}