src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),

    path("foods/", include("foods.urls")),
    path("orders/", include("orders.urls")),
    path("dashboard/", include("panel.urls")),

    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("about/", AboutUsTemplateView.as_view(), name="about_us"),
    path("", IndexTemplateView.as_view(), name="index"),
]

src/foods/urls.py
from django.urls import path

from .views import *


app_name = "foods"


urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("category/<int:id>/", CategoryDetailView.as_view(), name="category_details"),
    path("search/", SearchView.as_view(), name="search"),
    path("<int:id>/", FoodDetailView.as_view(), name="food_details"),
    path("menu/", MenuListView.as_view(), name="menu")
]

src/orders/urls.py
from django.urls import path
from .views import *


app_name = "orders"


urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order_list"),
    path("cart/", cart, name="cart"),
    path("set/", SetOrderView.as_view(), name="set_order"),
    path("", IndexView.as_view(), name="index"),
    path("<str:datetime>/", OrderDetailView.as_view(), name="order_details"),
]

src/panel/urls.py
from django.urls import path

from .views import *



app_name = "panel"



authentication_urls = [
    path('login/', LoginView.as_view(), name='login'),
    path('send-otp/', SendOTPView.as_view(), name="send-otp"),
    path('logout/', logout, name="logout"),
]


dashboard_urls = [
    path("order/<int:order_id>/edit/", EditOrders.as_view(), name="edit_order"),
    path("order/<int:order_id>/approve/", approve_order, name="approve_order"),
    path("order/<int:order_id>/reject/", reject_order, name="reject_order"),
    path("order/<int:order_id>/pay/", pay_order, name="pay_order"),
    path("order/<int:order_id>/deliver/", deliver_order, name="deliver_order"),
    path("order/<int:order_id>/take/", take_responsibility, name="take_responsibility"),
    path("",dashboard, name="dashboard"),
]


analytics_urls = [
    path("analytics-api/", JsonAPI.as_view(), name="analytics-api"),
    path("analytics/", analytics, name="analytics"),
    path("download/<str:dataset_name>", download_dataset, name="dataset_download"),
]



urlpatterns = [
    *authentication_urls,
    *analytics_urls,
    *dashboard_urls
]

src/orders/models.py
from django.db import models

from core.models import BaseModel
from foods.models import Food
from users.models import User


class Table(BaseModel):
    name = models.CharField(unique=True, max_length=25)
    is_reserved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name} ({'reserved' if self.is_reserved else 'empty'})"

    @classmethod
    def get_available_table(cls):
        tables = cls.objects.all()
        for table in tables:
            if table.is_reserved is False:
                return table



class Order(BaseModel):
    customer = models.ForeignKey(User, models.PROTECT)
    table = models.ForeignKey(Table, on_delete=models.SET_NULL, null=True)
    discount = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)
    status_field = models.TextChoices("Status","Pending Rejected Approved Delivered Paid")
    status = models.CharField(choices=status_field.choices, max_length=10,default="Pending")
    responsible_staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="assigned_orders")

    @property
    def price(self):
        return sum([item.final_price for item in self.orderitem_set.all()])

    @property
    def final_price(self):
        return round(self.price / 100 * (self.discount or 100), 2)

    def __str__(self) -> str:
        return f"{self.customer}"

    @property
    def get_url_id(self):
        return self.created_at.strftime("%Y%m%d%H%M%S")


    def approve(self):
        self.status = "Approved"
        self.save()
    def reject(self):
        self.status = "Rejected"
        self.save()
    def deliver(self):
        self.status = "Delivered"
        self.save()
    def pay(self):
        self.status = "Paid"
        self.save()

    def take_responsibility(self, staff:User):
        self.responsible_staff = staff
        self.save()

    def save(self, check_items=True):
        if check_items:
            if not self.price:
                raise SystemError("No price given")
        super().save()


class OrderItem(BaseModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    unit_price = models.DecimalField(decimal_places=2, max_digits=5)
    discount = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)

    @property
    def final_price(self):
        return round(((100-self.discount)/100*self.unit_price)*self.quantity, 2)

    def __str__(self) -> str:
        return f"{self.quantity}"

    def save(self, *args, **kwargs):
        related_order_items = OrderItem.objects.filter(order=self.order, food=self.food).exclude(id=self.id)
        if len(related_order_items):
            total_quantity = sum([item.quantity for item in related_order_items])
            for item in related_order_items:
                item.delete()
            self.quantity = total_quantity + self.quantity
        super().save(*args, **kwargs)

src/panel/views/analytics.py
import json
from datetime import datetime,timedelta

from django.http import Http404
from django.views import View
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin

from dynamic_menu.models import Configuration
from ..analytics.datasets import *
from ..analytics import *




datasets = {
    "orderitems" : export_order_items_to_csv,
    "orders" : export_orders_to_csv,
}



def download_dataset(request, dataset_name):
    if dataset_name in datasets:
        return datasets[dataset_name](request)
    else:
        raise Http404



@permission_required("analytics", raise_exception=True)
def analytics(request):
    context = {
        "peak_hours": get_top_peak_hours(),
        "sales_total":sales_total(),
        "datasets": datasets.keys()
    }
    return render(request, "panel/analytics.html", context)



def get_analytics_data():
    context = {
        "sales": {
            "comparative":{
                "day" :  sales_compar_day(),
                "week":  sales_compar_week(),
                "month": sales_compar_month(),
                "year":  sales_compar_year(),
            },
            "relative": {
                "day": sales_rel_day(),
                "week": sales_rel_week(),
                "month": sales_rel_month(),
                "year": sales_rel_year(),
            }
        },

        "items":{**food_items()},

        "orders": {**count_orders()},

        "categories": {**category_items()},

        "customer-sales":{
            "relative": {
                "week":  customerSales_rel(7),
                "month": customerSales_rel(30),
                "year":  customerSales_rel(365),
            }
        },
        "unique-customers": {
            "relative": {
                "week": unique_customers_rel(7),
                "month": unique_customers_rel(30),
            }
        },
        "others":{
            "relative" : {
                "peak-hour": get_peak_hours(),
                "staff-orders-week": {"new":user_order_counts(7), "old":None},
                "staff-orders-month": {"new":user_order_counts(30), "old":None},
                "order-status-week": {"new":order_status_counts(7), "old":None},
                "order-status-month": {"new":order_status_counts(30), "old":None},
            }
        }
    }
    return HttpResponse(json.dumps(context))



class JsonAPI(PermissionRequiredMixin, View):
    permission_required = ("analytics",)

    _conf = None
    last_update = datetime.now()
    current_data = None
    @property
    def configurations(self):
        if not self._conf:
            self._conf = Configuration.objects.first()
        return self._conf


    def get(self, request):
        if (not self.current_data)  or  (self.last_update + timedelta(hours=self.configurations.analytics_refresh)  <  datetime.now()):
            self.current_data = get_analytics_data()
            self.last_update = datetime.now()
        return self.current_data

src/panel/views/authentication.py
import json
import random
from typing import Any
from django.http import HttpRequest, HttpResponse, JsonResponse

from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views import View
from django.views.generic import FormView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (login as django_login, logout as django_logout)
from django.core.cache import caches

from users.models import User, Client
from ..forms import UserLogInForm



AUTH_CACHE = caches["default"]



def generate_2fa():
    return "".join(random.choices("0123456789", k=6))



class LoginView(FormView):

    template_name = 'panel/login.html'
    form_class = UserLogInForm
    client_success_url = reverse_lazy("foods:menu")
    staff_success_url = reverse_lazy("panel:dashboard")

    def dispatch(self, request, *args, **kwargs):
        if isinstance(request.user, User):
            return redirect("panel:dashboard")
        return super().dispatch(request, *args, **kwargs)

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        print(list(request.POST.items()))
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        cd = form.cleaned_data
        phone = str(cd['phone'])
        code = str(cd["otp_code"])
        cache_code = AUTH_CACHE.get(phone)
        if cache_code != code:
            form.add_error("otp_code", "Invalid code")
            return super().form_invalid(form)
        user = User.objects.filter(phone=phone).first()
        if not user:  # User is not staff, hence we create a Client (unusable password)
            user = Client.objects.create(phone=phone)
        django_login(self.request, user, "users.auth.UserAuthBackend")
        return super().form_valid(form)

    def get_success_url(self) -> str:
        if self.request.user.is_staff:
            return self.staff_success_url
        return self.client_success_url


class SendOTPView(View):
    def post(self, request):
        data = json.loads(request.body)
        phone = data.get("phone")
        AUTH_CACHE.set(phone, generate_2fa())
        return JsonResponse({"result":"ok"})


@login_required
def logout(request):
    django_logout(request)
    return redirect("index")

src/panel/views/dashboard.py
from django.db.models import Case, CharField, Value, When
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import View

from foods.models import Food
from orders.models import Order, Table, OrderItem
from ..forms import EditOrderForm, EditOrderItemForm, AddOrderItemForm,SearchbyDate




@login_required(login_url="panel:login")
@permission_required("orders.view_order", raise_exception=True)
def dashboard(request):
    ALL_ORDERS = Order.objects.all()
    orders = ALL_ORDERS.annotate(
        status_order=Case(
            When(status="Pending", then=Value(1)),
            When(status="Approved", then=Value(2)),
            When(status="Delivered", then=Value(3)),
            When(status="Rejected", then=Value(4)),
            When(status="Paid", then=Value(5)),
            default=Value(1),
            output_field=CharField(),
        )
    ).order_by('status_order')
    tables = Table.objects.all()
    form = SearchbyDate()
    context = {
        'orders': orders,
        'orders_by_date': ALL_ORDERS[::-1],
        'orders_user': ALL_ORDERS.filter(responsible_staff=request.user),
        'tables': tables,
        "name": request.user.first_name,
        "date_form": form
    }
    if request.method == 'POST':
        form = SearchbyDate(request.POST)
        if form.is_valid():
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            context['orders_between'] = ALL_ORDERS.filter(
                created_at__date__gte = start,
                created_at__date__lt = end
            )
        else:
            context["orders_between"] = {}
        context["date_form"] = form
    return render(request,'panel/dashboard.html', context)



class EditOrders(PermissionRequiredMixin,View):
    permission_required = ("orders.change_order",)
    def dispatch(self, request, order_id:int):
        self.order = get_object_or_404(Order, id=order_id)
        self.order_items = self.order.orderitem_set.all()
        return super().dispatch(request, order_id)

    def get(self, request, order_id:int):
        form =EditOrderForm(instance=self.order)
        item_forms = []
        for item in self.order_items:
            item_forms.append(EditOrderItemForm(instance=item, initial={"id":item.id}))
        foods = self.order_items.values_list('food', flat=True)
        foods2 = Food.objects.filter(is_active=False).values_list('id', flat=True)
        foods = (*foods, *foods2)
        add_item_form = AddOrderItemForm(exclude=foods)
        context = {'form':form, 'order':self.order, 'orderitems':item_forms, "add_item_form":add_item_form}
        return render(request,'panel/dashboard_editoreder.html',context)

    def post(self, request, order_id):
        # update order main info
        if request.POST.get("order"):
            form = EditOrderForm(request.POST, instance=self.order)
            if form.is_valid():
                form.save()
                return redirect("panel:dashboard")
            else:
                form.add_error(None,"Invalid input")
        # update order items
        elif request.POST.get("orderitem"):
            item = OrderItem.objects.get(id=request.POST["id"])
            if request.POST["orderitem"] == "delete":
                item.delete()
            else:
                itemform = EditOrderItemForm(request.POST, instance=item)
                if itemform.is_valid():
                    cd=itemform.cleaned_data
                    item.quantity = cd["quantity"]
                    item.food = cd["food"]
                    item.save()
                else:
                    itemform.add_error(None,"Invalid input")
        # add new item
        elif request.POST.get("add_item"):
            form = AddOrderItemForm(data=request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                unit_price = cd["food"].price
                discount = cd["food"].discount
                item = OrderItem(
                    food=cd["food"],
                    quantity=cd["quantity"],
                    unit_price=unit_price,
                    discount=discount,
                    order=self.order,
                ).save()
        return redirect("panel:edit_order",order_id=order_id)



def simple_action(view_func):
    @permission_required('orders.change_order', raise_exception=True)
    def _wrapped_view(request, order_id, *args, **kwargs):
        response = view_func(request, order_id, *args, **kwargs)
        return redirect("panel:dashboard")
    return _wrapped_view


@simple_action
def approve_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.approve()
    order.take_responsibility(request.user)

@simple_action
def reject_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.reject()

@simple_action
def pay_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.pay()

@simple_action
def deliver_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.deliver()

@simple_action
def take_responsibility(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.take_responsibility(request.user)

src/templates/panel/dashboard_base.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Dashboard
{% endblock title %}



{% block navbar %}
{% endblock navbar %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow py-2 col-md-9">
    <a class="navbar-brand ml-4" href="/">
        <img src="{{ maininfo.icon.url }}" alt="" class="navbar-brand" width="50px">
    </a>
    <a class="navbar-brand" href="/">{{ maininfo.title }}</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-4 mt-2">
                <a class="nav-link" href="{% url 'foods:category_list' %}">Categories</a>
            </li>
            <li class="nav-item mx-4 mt-2">
                <a class="nav-link" href="{% url 'foods:menu' %}">Menu</a>
            </li>
            {% if perms.analytics %}
            <li class="nav-item mx-3 mt-2">
                <a class="nav-link" href="{% url 'panel:analytics' %}">Analytics</a>
            </li>
            {%endif%}
            <li class="nav-item ml-2 mr-5 mt-2">
                <a href="{% url 'panel:logout' %}" class="ml-4 mt-1 btn btn-primary btn-sm w-100">Logout</a>
            </li>
        </ul>
    </div>
</nav>


<style>
    /* Custom CSS */
    @media (min-width: 768px) {
        .sidebar {
            width: 25%;
            position:fixed;
            top: 0;
            right: 0;
            height: 100vh;
            border-left: 1px;
        }
    }

    @media (max-width: 767.98px) {
        .sidebar {
            position: static;
            width: 100%;
            margin-top: 20px;
        }
    }

    select {
        display: block;
        width: 100%;
        padding: 25px 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
}

</style>




<div class="">
    <div class="container-fluid">
        <div class="row">

            {% block dashboard_content %}
            {% endblock dashboard_content %}


            <div class="col-md-3 sidebar border-left border-top bg-light py-4 d-flex flex-column justify-content-center">
                <!-- Sidebar content -->
                <p class="d-flex justify-content-center h5">Welcome {% if name %}"{{name}}"{% endif %}</p>
                <hr>
                <li class="list-group-item px-1 text-center"><a class="nav-link" href="{% url 'panel:dashboard' %}">Dashboard</a></li>
                <li class="list-group-item px-1 text-center"><a class="nav-link" href="{% url 'foods:category_list' %}">Categories</a></li>
                <li class="list-group-item px-1 text-center"><a class="nav-link" href="{% url 'foods:menu' %}">Menu</a></li>
                {% if perms.analytics %}
                <li class="list-group-item px-1 text-center"><a class="nav-link" href="{% url 'panel:analytics' %}">Analytics</a></li>
                {%endif%}
                <li class="list-group-item px-3">
                    <form action="{% url 'foods:search' %}" method="get">
                        <input type="search" name="searched" placeholder="search in foods..." class="form-control me-2">
                    </form>
                </li>

                <li class="list-group-item px-3"><a href="{% url 'panel:logout' %}" class="btn btn-primary btn-block">Logout</a></li>
                <div class="my-lg-4"></div>
            </div>



        </div>
    </div>
</div>



{% block footer %}
{% endblock footer %}
<div class="py-3 bg-light col-md-9 border-top">
    <div class="container">
        <div class="row justify-content-between align-items-center text-center">
            <div class="col-md-3 text-md-left mb-3 mb-md-0">
                <img src="{{ maininfo.icon.url }}" width="100" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, Pigga Landing page" class="mb-0">
            </div>
            <div class="col-md-9 text-md-right">
                {% if perms.analytics %}
                <a href="{% url 'panel:analytics' %}" class="link text-primary pr-5"><small class="font-weight-bold">Analytics</small></a>
                {%endif%}
                <a href="{% url 'orders:cart' %}" class="link text-primary pr-5"><small class="font-weight-bold">Cart</small></a>
                <a href="{% url 'orders:index' %}" class="link text-primary pr-4"><small class="font-weight-bold">Orders</small></a>
                <a href="{% url 'foods:menu' %}" class="link text-primary px-3"><small class="font-weight-bold">Menu</small></a>
                <a href="{% url 'foods:category_list' %}" class="link text-primary px-3"><small class="font-weight-bold">Categories</small></a>
            </div>
        </div>
    </div>
</div>

<footer class="border border-dark border-left-0 border-right-0 border-bottom-0 py-2 bg-dark col-md-9">
    <div class="container">
        <div class="row align-items-center text-center text-md-left">
            <div class="col">
                <p class="mb-0 small">© <script>document.write(new Date().getFullYear())</script>, <a href="https://github.com/Ramin-RX7/CafeMenu" target="_blank">Group1</a>  All rights reserved </p>
            </div>
            <div class="d-none d-md-block">
                <h6 class="small mb-0">
                    {% for app_name,link in socials.items %}
                        <a href="{{link}}" class="px-2"><i class="ti-{{app_name}}"></i></a>
                    {% endfor %}
                </h6>
            </div>
        </div>
    </div>
</footer>


{% endblock %}

src/templates/panel/dashboard_editoreder.html
{% extends 'panel/dashboard_base.html' %}
{% load static %}
{% block dashboard_content %}



<div class="mx-5 col-md-9 py-5">
    <h2 class="mb-5">Order Info</h2>
    <form action="{% url 'panel:edit_order' order_id=order.id %}" method="POST" class="d-flex mb-5 mt-2">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <button type="submit" class="btn btn-primary mx-5" name="order" value="order">update</button>
    </form>

    <hr>
    <hr>

    <h2 class="my-4">Items:</h2>
    <div class="row">
        {% for itemform in orderitems %}
        <div class="col-md-6">
            <form action="{% url 'panel:edit_order' order_id=order.id %}" method="POST" class="d-flex my-4">
                <table>
                    {% csrf_token %}
                    {{ itemform.as_table }}
                </table>
                <br>
                <button type="submit" class="mx-1 my-1 btn btn-primary" name="orderitem" value="update">update</button>
                <button type="submit" class="mx-1 my-1 btn btn-outline-primary" name="orderitem" value="delete">delete</button>
            </form>
        </div>
        {%endfor%}
    </div>
    <hr><hr>

    <h2 class="my-3">Add item</h2>
    <div class="row">
        <div class="col-md-6">
            <form action="{% url 'panel:edit_order' order.id %}" method="post">
                {% csrf_token %}
                <div class="d-flex my-3 align-items-center">
                    <label for="{{ add_item_form.food.id_for_label }}" class="h4 mx-4">Food:</label>
                    <select name="{{ add_item_form.food.name }}" class="" required>
                        {% for food in add_item_form.food.field.choices %}
                            <option value="{{ food.0 }}">{{ food.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="d-flex my-3 align-items-center">
                    <label for="{{ add_item_form.food.id_for_label }}" class="h4 mx-4">Quantity:</label>
                    {{add_item_form.quantity}}
                </div>
                <button type="submit" class="mx-1 my-1 btn btn-primary" name="add_item" value="add_item">add</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

src/templates/panel/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}

src/templates/panel/user_verify.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section id="book-table" class="bg-white">
    <div class="container">
        <div class="row align-items-center" style="flex-direction: column;">
            <div class="col-md-6">
                <form action="{% url 'panel:user_verify' %}" method="post">
                    {% csrf_token %}
                    {{ form.errors }}
                    {{ form.otp }}
                    <button type="submit" value="submit" class="btn btn-primary btn-block my-4 py-2"><div class="h4">Verify</div></button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

src/templates/panel/verify.html
{% extends 'base.html' %}
{% block content %}


<section id="book-table" class="bg-white">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <form action="{% url 'panel:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{form.as_p}}
                    </div>
                    <button type="submit" value="submit" class="btn btn-primary btn-block">Verify</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}